# Generated by Django 4.0.1 on 2022-01-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooking', '0002_remove_book_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='details',
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Renting', 'Renting'), ('Not Renting', 'Not Renting')], max_length=200, null=True),
        ),
    ]
